### ISSUE TITLE
App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [paulproteus/meteor-todos-sandstorm#1]
@paulproteus

I figured we could use the same graphics provided in the icons folder. I would love to know if there are higher res ones and I can export those for you at the correct sizes.

![meteortodo-preview1](https://cloud.githubusercontent.com/assets/855341/9260190/1873938e-41bb-11e5-9a97-33c3b2500fe5.png)

**Comment by paulproteus** [comment]
Closed by #3 I believe now. Thanks for filing this.
